const char* black_white_src = "#version 330 core\n"
"\n"
"in vec2 TexCoord;\n"
"out vec4 FragColor;\n"
"\n"
"uniform sampler2D screenTexture;\n"
"\n"
"void main()\n"
"{\n"
"    vec3 color = texture(screenTexture, TexCoord).rgb;\n"
"    \n"
"    float gray = dot(color, vec3(0.299, 0.587, 0.114));\n"
"    \n"
"    FragColor = vec4(vec3(gray), 1.0);\n"
"}\n"
;

const char* blur_src = "#version 330 core\n"
"\n"
"in vec2 TexCoord;\n"
"out vec4 FragColor;\n"
"\n"
"uniform sampler2D screenTexture;\n"
"uniform vec2 resolution;\n"
"\n"
"void main()\n"
"{\n"
"    vec2 texelSize = 1.0 / resolution;\n"
"    vec3 result = vec3(0.0);\n"
"    float total = 0.0;\n"
"\n"
"    // 5x5 Gaussian-ish kernel\n"
"    const int radius = 6;\n"
"    for (int x = -radius; x <= radius; ++x) {\n"
"        for (int y = -radius; y <= radius; ++y) {\n"
"            float weight = 1.0 - (length(vec2(x, y)) / (float(radius) * 1.5));\n"
"            weight = max(weight, 0.0);\n"
"\n"
"            vec2 offset = vec2(float(x), float(y)) * texelSize;\n"
"            result += texture(screenTexture, TexCoord + offset).rgb * weight;\n"
"            total += weight;\n"
"        }\n"
"    }\n"
"\n"
"    result /= total;\n"
"\n"
"    FragColor = vec4(result, 1.0);\n"
"}\n"
;

const char* glitch_src = "#version 330 core\n"
"\n"
"in vec2 TexCoord;\n"
"out vec4 FragColor;\n"
"\n"
"uniform sampler2D screenTexture;\n"
"uniform float time;\n"
"\n"
"float rand(vec2 p)\n"
"{\n"
"    return fract(sin(dot(p, vec2(12.9898, 78.233))) * 43758.5453);\n"
"}\n"
"\n"
"void main()\n"
"{\n"
"    vec2 uv = TexCoord;\n"
"\n"
"    // Random horizontal glitch lines\n"
"    float line = floor(uv.y * 100.0);\n"
"\n"
"    if (rand(vec2(line, floor(time * 15.0))) > 0.95)\n"
"    {\n"
"        uv.x += (rand(vec2(line, time)) - 0.5) * 0.1;\n"
"    }\n"
"\n"
"    // Random blocks\n"
"    vec2 block = floor(uv * vec2(16.0, 10.0));\n"
"\n"
"    if (rand(block + floor(time * 10.0)) > 0.97)\n"
"    {\n"
"        uv.x += (rand(block) - 0.5) * 0.15;\n"
"    }\n"
"\n"
"    // Get the image\n"
"    vec3 color = texture(screenTexture, uv).rgb;\n"
"\n"
"    // Noise\n"
"    color += (rand(uv * time * 300.0) - 0.5) * 0.04;\n"
"\n"
"    // Random flash\n"
"    if (rand(vec2(floor(time * 8.0), 1.0)) > 0.98)\n"
"    {\n"
"        color *= 1.3;\n"
"    }\n"
"\n"
"    FragColor = vec4(color, 1.0);\n"
"}\n"
;

const char* vhs_src = "#version 330 core\n"
"\n"
"in vec2 TexCoord;\n"
"out vec4 FragColor;\n"
"\n"
"uniform sampler2D screenTexture;\n"
"uniform float time;\n"
"uniform vec2 resolution;\n"
"\n"
"float hash(vec2 p)\n"
"{\n"
"    return fract(sin(dot(p, vec2(127.1, 311.7))) * 43758.5453);\n"
"}\n"
"\n"
"void main()\n"
"{\n"
"    vec2 uv = TexCoord;\n"
"\n"
"    // Subtle horizontal tracking distortion\n"
"    float line = floor(uv.y * 50.0);\n"
"    float noise = hash(vec2(line, floor(time * 8.0)));\n"
"\n"
"    uv.x += (noise - 0.5) * 0.003;\n"
"\n"
"    // Occasional small tracking glitch\n"
"    float glitch = step(0.995, hash(vec2(floor(time * 5.0), line)));\n"
"\n"
"    uv.x += glitch * (hash(vec2(line, time)) - 0.5) * 0.025;\n"
"\n"
"    // Original image — no chromatic aberration\n"
"    vec3 color = texture(screenTexture, uv).rgb;\n"
"\n"
"    // Subtle scanlines\n"
"    float scanline = sin(uv.y * resolution.y * 1.5);\n"
"    color *= 1.0 - scanline * 0.025;\n"
"\n"
"    // Fine VHS noise\n"
"    float grain = hash(uv * resolution + time * 20.0);\n"
"    color += (grain - 0.5) * 0.025;\n"
"\n"
"    // Slight brightness flicker\n"
"    color *= 0.99 + 0.01 * sin(time * 8.0);\n"
"\n"
"    // Very subtle vignette\n"
"    vec2 center = uv - 0.5;\n"
"    float vignette = 1.0 - dot(center, center) * 0.25;\n"
"    color *= vignette;\n"
"\n"
"    FragColor = vec4(color, 1.0);\n"
"}\n"
;

const char* chromatic_src = "#version 330 core\n"
"\n"
"in vec2 TexCoord;\n"
"out vec4 FragColor;\n"
"\n"
"uniform sampler2D screenTexture;\n"
"\n"
"const vec2 OFFSET = vec2(0.005, 0.0);\n"
"\n"
"void main() {\n"
"    float r = texture(screenTexture, TexCoord - OFFSET).r;\n"
"    float g = texture(screenTexture, TexCoord).g;\n"
"    float b = texture(screenTexture, TexCoord + OFFSET).b;\n"
"\n"
"    FragColor = vec4(r, g, b, 1.0);\n"
"}\n"
;

const char* scanline_src = "#version 330 core\n"
"\n"
"in vec2 TexCoord;\n"
"out vec4 FragColor;\n"
"\n"
"uniform sampler2D screenTexture;\n"
"float strength = 0.5;\n"
"\n"
"void main()\n"
"{\n"
"    vec3 color = texture(screenTexture, TexCoord).rgb;\n"
"\n"
"    float scanline = sin(TexCoord.y * 1200.0);\n"
"\n"
"    color *= 1.0 - scanline * strength;\n"
"\n"
"    FragColor = vec4(color, 1.0);\n"
"}\n"
;

const char* film_grain_src = "#version 330 core\n"
"\n"
"in vec2 TexCoord;\n"
"out vec4 FragColor;\n"
"\n"
"uniform sampler2D screenTexture;\n"
"uniform float time;\n"
"uniform float grainIntensity = 0.15;\n"
"\n"
"float hash(vec2 p) {\n"
"    return fract(sin(dot(p, vec2(12.9898, 78.233))) * 43758.5453123);\n"
"}\n"
"\n"
"void main() {\n"
"    vec3 color = texture(screenTexture, TexCoord).rgb;\n"
"    float grain = hash(TexCoord * time);\n"
"    color += (grain - 0.5) * grainIntensity;\n"
"    FragColor = vec4(color, 1.0);\n"
"}\n"
;

const char* vignette_src = "#version 330 core\n"
"\n"
"in vec2 TexCoord;\n"
"out vec4 FragColor;\n"
"\n"
"uniform sampler2D screenTexture;\n"
"uniform float vignetteStrength = 2;\n"
"uniform float vignetteRadius = 0.75;\n"
"\n"
"void main() {\n"
"    vec3 color = texture(screenTexture, TexCoord).rgb;\n"
"    float dist = length(TexCoord - vec2(0.5));\n"
"    float vig = smoothstep(vignetteRadius, vignetteRadius - 0.4, dist);\n"
"    color *= mix(1.0 - vignetteStrength, 1.0, vig);\n"
"    FragColor = vec4(color, 1.0);\n"
"}\n"
;

const char* pixel_src = "#version 330 core\n"
"\n"
"in vec2 TexCoord;\n"
"out vec4 FragColor;\n"
"\n"
"uniform sampler2D screenTexture;\n"
"uniform vec2 resolution;\n"
"uniform float pixelSize = 8.0;\n"
"\n"
"void main() {\n"
"    vec2 grid = resolution / pixelSize;\n"
"    vec2 snappedUV = floor(TexCoord * grid) / grid;\n"
"    FragColor = vec4(texture(screenTexture, snappedUV).rgb, 1.0);\n"
"}\n"
;

