// just a file containing the global strings of baked-in shaders

const char* vhs_shader_src = "#version 330 core\n"
"\n"
"in vec2 TexCoord;\n"
"out vec4 FragColor;\n"
"\n"
"uniform sampler2D screenTexture;\n"
"uniform float time;       // pass elapsed time in seconds\n"
"uniform vec2 resolution;  // screen resolution\n"
"\n"
"// Simple pseudo-random hash\n"
"float hash(vec2 p)\n"
"{\n"
"    return fract(sin(dot(p, vec2(127.1, 311.7))) * 43758.5453);\n"
"}\n"
"\n"
"void main()\n"
"{\n"
"    vec2 uv = TexCoord;\n"
"\n"
"    // --- Tracking distortion (horizontal jitter bands) ---\n"
"    float trackingNoise = hash(vec2(floor(uv.y * 40.0), time * 4.0));\n"
"    float tracking = (trackingNoise - 0.5) * 0.004;\n"
"    // Occasional bigger glitch band\n"
"    float glitchBand = step(0.995, hash(vec2(floor(uv.y * 10.0), floor(time * 6.0))));\n"
"    tracking += glitchBand * (hash(vec2(time)) - 0.5) * 0.05;\n"
"    uv.x += tracking;\n"
"\n"
"    // --- Chromatic aberration (color channel split) ---\n"
"    float aberration = 0.004;\n"
"    float r = texture(screenTexture, uv + vec2(aberration, 0.0)).r;\n"
"    float g = texture(screenTexture, uv).g;\n"
"    float b = texture(screenTexture, uv - vec2(aberration, 0.0)).b;\n"
"    vec3 color = vec3(r, g, b);\n"
"\n"
"    // --- Scanlines ---\n"
"    float scanline = sin(uv.y * resolution.y * 1.5) * 0.08;\n"
"    color -= scanline;\n"
"\n"
"    // --- Static noise ---\n"
"    float noise = hash(uv * time) * 0.08;\n"
"    color += noise - 0.04;\n"
"\n"
"    // --- Slight vertical roll / brightness flicker ---\n"
"    float flicker = 0.97 + 0.03 * sin(time * 10.0);\n"
"    color *= flicker;\n"
"\n"
"    // --- Vignette ---\n"
"    vec2 center = uv - 0.5;\n"
"    float vignette = 1.0 - dot(center, center) * 0.6;\n"
"    color *= vignette;\n"
"\n"
"    // --- Slight desaturation + contrast bump for that washed VHS look ---\n"
"    float gray = dot(color, vec3(0.299, 0.587, 0.114));\n"
"    color = mix(color, vec3(gray), 0.15);\n"
"    color = clamp((color - 0.5) * 1.1 + 0.5, 0.0, 1.0);\n"
"\n"
"    FragColor = vec4(color, 1.0);\n"
"}\n";

const char* black_white_shader_src = "#version 330 core\n"
"\n"
"in vec2 TexCoord;\n"
"out vec4 FragColor;\n"
"\n"
"uniform sampler2D screenTexture;\n"
"\n"
"void main()\n"
"{\n"
"    vec3 color = texture(screenTexture, TexCoord).rgb;\n"
"    \n"
"    float gray = dot(color, vec3(0.299, 0.587, 0.114));\n"
"    \n"
"    FragColor = vec4(vec3(gray), 1.0);\n"
"}\n";