// just a file containing the global strings of baked-in shaders


const char* to_screen_vertex_src = 
                        "#version 330 core\n"
                        "\n"
                        "layout(location = 0) in vec2 aPos;\n"
                        "layout(location = 1) in vec2 aTexCoord;\n"
                        "\n"
                        "out vec2 TexCoord;\n"
                        "\n"
                        "uniform vec2 scale;\n"
                        "\n"
                        "void main()\n"
                        "{\n"
                        "    TexCoord = aTexCoord;\n"
                        "    gl_Position = vec4(aPos * scale, 0.0, 1.0);\n"
                        "}\n";

const char* filter_vertex_src = 
                        "#version 330 core\n"
                        "\n"
                        "layout(location = 0) in vec2 aPos;\n"
                        "layout(location = 1) in vec2 aTexCoord;\n"
                        "\n"
                        "out vec2 TexCoord;\n"
                        "\n"
                        "void main()\n"
                        "{\n"
                        "    TexCoord = aTexCoord;\n"
                        "    gl_Position = vec4(aPos, 0.0, 1.0);\n"
                        "}\n";

const char* yuv_to_rgb_src = 
                    "#version 330 core\n"
                    "in vec2 TexCoord;\n"

                    "out vec4 FragColor;\n"

                    "uniform sampler2D texY;\n"
                    "uniform sampler2D texU;\n"
                    "uniform sampler2D texV;\n"

                    "void main()\n"
                    "{\n"
                    "    vec2 uv = vec2(TexCoord.x, 1.0 - TexCoord.y);\n"
                    "    float y = texture(texY, uv).r;\n"

                    "    float u = texture(texU, uv).r - 0.5;\n"
                    "    float v = texture(texV, uv).r - 0.5;\n"

                    "    vec3 rgb;\n"

                    "    rgb.r = y + 1.402 * v;\n"
                    "    rgb.g = y - 0.344136 * u - 0.714136 * v;\n"
                    "    rgb.b = y + 1.772 * u;\n"

                    "    FragColor = vec4(rgb, 1.0);\n"
                    "}\n";

const char* to_screen_src = "#version 330 core\n"
"\n"
"in vec2 TexCoord;\n"
"out vec4 FragColor;\n"
"\n"
"uniform sampler2D screenTexture;\n"
"\n"
"void main()\n"
"{\n"
"    FragColor = texture(screenTexture, TexCoord);\n"
"}\n";


const char* vhs_src = "#version 330 core\n"
"\n"
"in vec2 TexCoord;\n"
"out vec4 FragColor;\n"
"\n"
"uniform sampler2D screenTexture;\n"
"uniform float time;       // pass elapsed time in seconds\n"
"uniform vec2 resolution;  // screen resolution\n"
"\n"
"// Simple pseudo-random hash\n"
"float hash(vec2 p)\n"
"{\n"
"    return fract(sin(dot(p, vec2(127.1, 311.7))) * 43758.5453);\n"
"}\n"
"\n"
"void main()\n"
"{\n"
"    vec2 uv = TexCoord;\n"
"\n"
"    // --- Tracking distortion (horizontal jitter bands) ---\n"
"    float trackingNoise = hash(vec2(floor(uv.y * 40.0), time * 4.0));\n"
"    float tracking = (trackingNoise - 0.5) * 0.004;\n"
"    // Occasional bigger glitch band\n"
"    float glitchBand = step(0.995, hash(vec2(floor(uv.y * 10.0), floor(time * 6.0))));\n"
"    tracking += glitchBand * (hash(vec2(time)) - 0.5) * 0.05;\n"
"    uv.x += tracking;\n"
"\n"
"    // --- Chromatic aberration (color channel split) ---\n"
"    float aberration = 0.004;\n"
"    float r = texture(screenTexture, uv + vec2(aberration, 0.0)).r;\n"
"    float g = texture(screenTexture, uv).g;\n"
"    float b = texture(screenTexture, uv - vec2(aberration, 0.0)).b;\n"
"    vec3 color = vec3(r, g, b);\n"
"\n"
"    // --- Scanlines ---\n"
"    float scanline = sin(uv.y * resolution.y * 1.5) * 0.08;\n"
"    color -= scanline;\n"
"\n"
"    // --- Static noise ---\n"
"    float noise = hash(uv * time) * 0.08;\n"
"    color += noise - 0.04;\n"
"\n"
"    // --- Slight vertical roll / brightness flicker ---\n"
"    float flicker = 0.97 + 0.03 * sin(time * 10.0);\n"
"    color *= flicker;\n"
"\n"
"    // --- Vignette ---\n"
"    vec2 center = uv - 0.5;\n"
"    float vignette = 1.0 - dot(center, center) * 0.6;\n"
"    color *= vignette;\n"
"\n"
"    // --- Slight desaturation + contrast bump for that washed VHS look ---\n"
"    float gray = dot(color, vec3(0.299, 0.587, 0.114));\n"
"    color = mix(color, vec3(gray), 0.15);\n"
"    color = clamp((color - 0.5) * 1.1 + 0.5, 0.0, 1.0);\n"
"\n"
"    FragColor = vec4(color, 1.0);\n"
"}\n";

const char* black_white_src = "#version 330 core\n"
"\n"
"in vec2 TexCoord;\n"
"out vec4 FragColor;\n"
"\n"
"uniform sampler2D screenTexture;\n"
"\n"
"void main()\n"
"{\n"
"    vec3 color = texture(screenTexture, TexCoord).rgb;\n"
"    \n"
"    float gray = dot(color, vec3(0.299, 0.587, 0.114));\n"
"    \n"
"    FragColor = vec4(vec3(gray), 1.0);\n"
"}\n";

const char* blur_src = "#version 330 core\n"
"\n"
"in vec2 TexCoord;\n"
"out vec4 FragColor;\n"
"\n"
"uniform sampler2D screenTexture;\n"
"uniform vec2 resolution;\n"
"\n"
"void main()\n"
"{\n"
"    vec2 texelSize = 1.0 / resolution;\n"
"    vec3 result = vec3(0.0);\n"
"    float total = 0.0;\n"
"\n"
"    // 5x5 Gaussian-ish kernel\n"
"    const int radius = 6;\n"
"    for (int x = -radius; x <= radius; ++x) {\n"
"        for (int y = -radius; y <= radius; ++y) {\n"
"            float weight = 1.0 - (length(vec2(x, y)) / (float(radius) * 1.5));\n"
"            weight = max(weight, 0.0);\n"
"\n"
"            vec2 offset = vec2(float(x), float(y)) * texelSize;\n"
"            result += texture(screenTexture, TexCoord + offset).rgb * weight;\n"
"            total += weight;\n"
"        }\n"
"    }\n"
"\n"
"    result /= total;\n"
"\n"
"    FragColor = vec4(result, 1.0);\n"
"}\n";

const char *glitch_src = "#version 330 core\n"
"\n"
"in vec2 TexCoord;\n"
"out vec4 FragColor;\n"
"\n"
"uniform sampler2D screenTexture;\n"
"uniform float time;\n"
"\n"
"float rand(vec2 p)\n"
"{\n"
"    return fract(sin(dot(p, vec2(12.9898,78.233))) * 43758.5453);\n"
"}\n"
"\n"
"void main()\n"
"{\n"
"    vec2 uv = TexCoord;\n"
"\n"
"    //-----------------------------\n"
"    // Random horizontal slices\n"
"    //-----------------------------\n"
"    float line = floor(uv.y * 140.0);\n"
"\n"
"    if(rand(vec2(line, floor(time * 18.0))) > 0.93)\n"
"    {\n"
"        uv.x += (rand(vec2(line, time)) - 0.5) * 0.12;\n"
"    }\n"
"\n"
"    //-----------------------------\n"
"    // Block corruption\n"
"    //-----------------------------\n"
"    vec2 block = floor(uv * vec2(20.0, 12.0));\n"
"\n"
"    if(rand(block + floor(time * 12.0)) > 0.96)\n"
"    {\n"
"        uv.x += (rand(block) - 0.5) * 0.18;\n"
"        uv.y += (rand(block + 3.1) - 0.5) * 0.04;\n"
"    }\n"
"\n"
"    //-----------------------------\n"
"    // RGB Split\n"
"    //-----------------------------\n"
"    float shift = 0.006;\n"
"\n"
"    vec2 rUV = uv + vec2( shift, 0.0);\n"
"    vec2 gUV = uv;\n"
"    vec2 bUV = uv - vec2( shift, 0.0);\n"
"\n"
"    float r = texture(screenTexture, rUV).r;\n"
"    float g = texture(screenTexture, gUV).g;\n"
"    float b = texture(screenTexture, bUV).b;\n"
"\n"
"    vec3 color = vec3(r, g, b);\n"
"\n"
"    //-----------------------------\n"
"    // Scanlines\n"
"    //-----------------------------\n"
"    float scan = sin(uv.y * 900.0) * 0.03;\n"
"    color -= scan;\n"
"\n"
"    //-----------------------------\n"
"    // White Noise\n"
"    //-----------------------------\n"
"    color += (rand(uv * time * 300.0) - 0.5) * 0.05;\n"
"\n"
"    //-----------------------------\n"
"    // Random Flash\n"
"    //-----------------------------\n"
"    if(rand(vec2(floor(time * 8.0), 1.0)) > 0.98)\n"
"    {\n"
"        color *= 1.4;\n"
"    }\n"
"\n"
"    FragColor = vec4(color, 1.0);\n"
"}\n";